### PR TITLE
add `yui` type to transpile to YUI Modules

### PR DESCRIPTION
**Pull request by caridy**
todo
- [x] tests
- [x] docs

### CODE REVIEW

**Comment by caridy** [comment]
This PR is subject to https://github.com/square/es6-module-transpiler/pull/78

**Comment by caridy** [comment]
All the tests were failing (from master). I have fixed 8 of them, and added one more that works for YUI, but the `coffee` test is still failing.

This PR is now ready to be merged considering that `es6-module-transpiler@0.3.4` was released today with the proper support for YUI.

**Comment by caridy** [comment]
any update on this?

**Comment by caridy** [comment]
@joefiorini thanks for merging this. Any chance we can this in NPM?

**Comment by okuryu** [comment]
@caridy I filed a ticket. #13

**Pull request merged**
