### PR TITLE
Add support for moduleName option to be a callback

### PR DESCRIPTION
**Pull request by lukemelia**
This PR adds support for the moduleName option to be a callback.

The callback is provided the default module name and should
return the desired module name. This is particularly useful
for adding or stripping module prefixes.

This commit also improves the default module naming by
stripping the cwd if it was specified in the files option.

@lukemelia/@kselden

### CODE REVIEW

**Comment by stefanpenner** [comment]
+10000

**Comment by joefiorini** [comment]
Thanks @lukemelia and @kselden! I just published a new release with this change as v0.3.0.

**Comment by lukemelia** [comment]
Sweet. Thanks, @joefiorini!

**Comment by stefanpenner** [comment]
:dancer:

**Pull request merged**
